export const USD_CNY_RATE = 6.7939;

export type B2BCatalogProduct = {
  id: string;
  slug: string;
  name: string;
  subtitle: string;
  species: "dog" | "cat" | "dog_cat";
  format: "chew" | "powder" | "oil" | "paste" | "dropper" | "tablet";
  category: "Joint" | "Digestive" | "Skin & coat" | "Calming" | "Immune" | "Daily wellness" | "Specialty";
  image: string;
  referenceCny?: number;
  moq?: number;
};

export function usdFromCny(cny: number) {
  return cny / USD_CNY_RATE;
}

export const B2B_CATALOG: B2BCatalogProduct[] = [
  {
    id: "hip-joint",
    slug: "hip-joint-mobility-chews",
    name: "Hip & Joint Mobility Chews",
    subtitle: "Soft-chew mobility support for adult and senior dogs.",
    species: "dog",
    format: "chew",
    category: "Joint",
    image: "/products/hip-joint-mobility-chews.png",
    referenceCny: 23,
    moq: 5,
  },
  {
    id: "probiotic-chews",
    slug: "probiotic-gut-health-chews",
    name: "Probiotic Gut Health Chews",
    subtitle: "Daily digestive support in an easy-to-position chew format.",
    species: "dog_cat",
    format: "chew",
    category: "Digestive",
    image: "/products/probiotic-gut-health-chews.png",
    referenceCny: 25,
    moq: 15,
  },
  {
    id: "skin-coat",
    slug: "skin-coat-salmon-chews",
    name: "Skin & Coat Chews + Salmon Oil",
    subtitle: "A coat-care soft chew designed for beauty and wellness ranges.",
    species: "dog_cat",
    format: "chew",
    category: "Skin & coat",
    image: "/products/skin-coat-salmon-chews.png",
    referenceCny: 14,
    moq: 50,
  },
  {
    id: "multivitamin-10",
    slug: "multivitamin-10-in-1-chews",
    name: "10-in-1 Multivitamin Chews",
    subtitle: "Broad daily wellness support for mainstream supplement lines.",
    species: "dog",
    format: "chew",
    category: "Daily wellness",
    image: "/products/multivitamin-10-in-1-chews.png",
    referenceCny: 11,
  },
  {
    id: "calming",
    slug: "calming-chews",
    name: "Calming Chews",
    subtitle: "Behavior and relaxation support for travel, separation and daily routines.",
    species: "dog",
    format: "chew",
    category: "Calming",
    image: "/products/calming-chews.png",
    referenceCny: 8.8,
    moq: 3000,
  },
  {
    id: "allergy",
    slug: "allergy-immune-chews",
    name: "Allergy & Immune Chews",
    subtitle: "Seasonal wellness and immune-positioned chewable support.",
    species: "dog_cat",
    format: "chew",
    category: "Immune",
    image: "/products/allergy-immune-chews.png",
    referenceCny: 15,
  },
  {
    id: "flea-tick-chews",
    slug: "flea-tick-defense-chews",
    name: "Flea & Tick Support Chews",
    subtitle: "A daily chew format for flea-and-tick support product ranges.",
    species: "dog",
    format: "chew",
    category: "Specialty",
    image: "/products/flea-tick-defense-chews.png",
    referenceCny: 22,
    moq: 50,
  },
  {
    id: "nad",
    slug: "nad-longevity-chews",
    name: "NAD+ Longevity Chews",
    subtitle: "A premium healthy-aging concept for differentiated wellness lines.",
    species: "dog",
    format: "chew",
    category: "Daily wellness",
    image: "/products/nad-longevity-chews.png",
  },
  {
    id: "omega-3",
    slug: "omega-3-wild-fish-oil",
    name: "Omega-3 Wild Fish Oil",
    subtitle: "Pump-format oil for skin, coat and daily nutritional support.",
    species: "dog_cat",
    format: "oil",
    category: "Skin & coat",
    image: "/products/omega-3-wild-fish-oil.png",
    referenceCny: 18,
    moq: 3000,
  },
  {
    id: "urinary",
    slug: "cat-urinary-support-drops",
    name: "Cat Urinary Support Drops",
    subtitle: "Dropper-format specialty support developed for feline ranges.",
    species: "cat",
    format: "dropper",
    category: "Specialty",
    image: "/products/cat-urinary-support-drops.png",
    referenceCny: 13,
    moq: 3000,
  },
  {
    id: "lysine-powder",
    slug: "cat-lysine-immune-powder",
    name: "Cat L-Lysine Immune Powder",
    subtitle: "Mix-in feline powder for immune and daily wellness positioning.",
    species: "cat",
    format: "powder",
    category: "Immune",
    image: "/products/cat-lysine-immune-powder.png",
    referenceCny: 20,
    moq: 3000,
  },
  {
    id: "hairball-chews",
    slug: "cat-hairball-control-chews",
    name: "Cat Hairball Control Chews",
    subtitle: "Palatable chewable support for feline hairball routines.",
    species: "cat",
    format: "chew",
    category: "Digestive",
    image: "/products/cat-hairball-control-chews.png",
    referenceCny: 18,
    moq: 3000,
  },
  {
    id: "goat-milk",
    slug: "lactoferrin-goat-milk-powder",
    name: "Lactoferrin Goat Milk Powder",
    subtitle: "Premium mix-in nutrition concept for dogs and cats.",
    species: "dog_cat",
    format: "powder",
    category: "Daily wellness",
    image: "/products/lactoferrin-goat-milk-powder.png",
    referenceCny: 16,
    moq: 3000,
  },
  {
    id: "collagen",
    slug: "multi-collagen-soft-chews",
    name: "Multi-Collagen Soft Chews",
    subtitle: "Collagen-led mobility and healthy-aging positioning.",
    species: "dog",
    format: "chew",
    category: "Joint",
    image: "/products/collagen-mobility-chews.png",
  },
  {
    id: "hairball-drops",
    slug: "cat-hairball-relief-drops",
    name: "Cat Hairball Relief Drops",
    subtitle: "Liquid hairball support for feline supplement portfolios.",
    species: "cat",
    format: "dropper",
    category: "Digestive",
    image: "/images/catalog/cat-hairball-drops.png",
    referenceCny: 8.8,
    moq: 3000,
  },
  {
    id: "cardio",
    slug: "cardio-support-chews",
    name: "Cardio Support Chews",
    subtitle: "Heart-health positioned soft chews for dog wellness ranges.",
    species: "dog",
    format: "chew",
    category: "Specialty",
    image: "/images/catalog/cardio-support-chews.png",
    referenceCny: 18,
    moq: 3000,
  },
  {
    id: "tear-stain",
    slug: "tear-stain-drops",
    name: "Tear Stain Drops",
    subtitle: "Dropper-format eye-area appearance support for dogs and cats.",
    species: "dog_cat",
    format: "dropper",
    category: "Specialty",
    image: "/images/catalog/tear-stain-drops.jpg",
    referenceCny: 25,
    moq: 3000,
  },
  {
    id: "turkey-tail-powder",
    slug: "turkey-tail-mushroom-powder",
    name: "Turkey Tail Mushroom Powder",
    subtitle: "Functional mushroom powder for immune-positioned pet products.",
    species: "dog_cat",
    format: "powder",
    category: "Immune",
    image: "/images/catalog/turkey-tail-powder.png",
    referenceCny: 18,
    moq: 3000,
  },
  {
    id: "ginkgo",
    slug: "ginkgo-extract-drops",
    name: "Ginkgo Extract Drops",
    subtitle: "Botanical liquid concept for premium feline wellness portfolios.",
    species: "cat",
    format: "dropper",
    category: "Daily wellness",
    image: "/images/catalog/ginkgo-drops.png",
    referenceCny: 12,
    moq: 3000,
  },
  {
    id: "lysine-liquid",
    slug: "cat-l-lysine-liquid-drops",
    name: "Cat L-Lysine Liquid Drops",
    subtitle: "Liquid feline immune support in a convenient dropper bottle.",
    species: "cat",
    format: "dropper",
    category: "Immune",
    image: "/images/catalog/cat-lysine-drops.jpg",
    referenceCny: 20,
    moq: 3000,
  },
  {
    id: "flea-tick-drops",
    slug: "flea-tick-support-drops",
    name: "Flea & Tick Support Drops",
    subtitle: "Liquid support format for cat and dog specialty ranges.",
    species: "dog_cat",
    format: "dropper",
    category: "Specialty",
    image: "/images/catalog/flea-tick-drops.png",
    referenceCny: 12,
    moq: 500,
  },
  {
    id: "hairball-paste",
    slug: "cat-hairball-paste",
    name: "Cat Hairball Paste",
    subtitle: "Paste-format hairball support for feline care programs.",
    species: "cat",
    format: "paste",
    category: "Digestive",
    image: "/images/catalog/cat-hairball-paste.png",
    referenceCny: 15,
    moq: 1000,
  },
  {
    id: "dental-powder",
    slug: "pet-dental-cleaning-powder",
    name: "Pet Dental Cleaning Powder",
    subtitle: "Mix-in oral-care powder for dog and cat daily routines.",
    species: "dog_cat",
    format: "powder",
    category: "Specialty",
    image: "/images/catalog/dental-powder.png",
    referenceCny: 15,
  },
  {
    id: "hemp-oil",
    slug: "hemp-seed-oil-drops",
    name: "Hemp Seed Oil Drops",
    subtitle: "Botanical oil format for calm and skin-and-coat positioning.",
    species: "dog_cat",
    format: "oil",
    category: "Calming",
    image: "/images/catalog/hemp-seed-oil.jpg",
    referenceCny: 12,
    moq: 3000,
  },
  {
    id: "probiotic-powder",
    slug: "pet-probiotic-powder",
    name: "Pet Probiotic Powder",
    subtitle: "Shelf-ready digestive powder for dogs and cats.",
    species: "dog_cat",
    format: "powder",
    category: "Digestive",
    image: "/images/catalog/probiotic-powder.png",
    referenceCny: 23,
    moq: 3000,
  },
  {
    id: "multivitamin-8",
    slug: "8-in-1-multivitamin-chews",
    name: "8-in-1 Multivitamin Chews",
    subtitle: "Daily vitality soft chews suitable for breed-focused programs.",
    species: "dog",
    format: "chew",
    category: "Daily wellness",
    image: "/images/catalog/multivitamin-8-in-1-chews.png",
    referenceCny: 16,
    moq: 5,
  },
  {
    id: "turkey-tail-chews",
    slug: "turkey-tail-mushroom-chews",
    name: "Turkey Tail Mushroom Chews",
    subtitle: "Functional mushroom chew for premium immune product lines.",
    species: "dog_cat",
    format: "chew",
    category: "Immune",
    image: "/images/catalog/turkey-tail-chews.png",
    referenceCny: 19,
    moq: 3000,
  },
  {
    id: "glucosamine-tablets",
    slug: "dog-glucosamine-tablets",
    name: "Dog Glucosamine Tablets",
    subtitle: "Tablet-format joint and mobility support for dog ranges.",
    species: "dog",
    format: "tablet",
    category: "Joint",
    image: "/images/catalog/dog-glucosamine-tablets.png",
    referenceCny: 17,
    moq: 3000,
  },
  {
    id: "cat-joint",
    slug: "cat-joint-support-drops",
    name: "Cat Joint Support Drops",
    subtitle: "Liquid joint-care support developed for feline use.",
    species: "cat",
    format: "dropper",
    category: "Joint",
    image: "/images/catalog/cat-joint-drops.jpg",
    referenceCny: 23,
    moq: 3000,
  },
  {
    id: "anti-inflammatory",
    slug: "anti-inflammatory-multivitamin-drops",
    name: "Anti-inflammatory Multivitamin Drops",
    subtitle: "Liquid daily-wellness concept for flexible private-label positioning.",
    species: "dog_cat",
    format: "dropper",
    category: "Daily wellness",
    image: "/images/catalog/anti-inflammatory-drops.png",
    referenceCny: 9,
    moq: 3000,
  },
];
